### ISSUE TITLE
1회 모임 안내 - 19/04/30(화) 19:00 [변경!]

### ISSUE THREAD

**Issue by tea7day** [tea7day/primorsk#1]
###
- 시간: **19/04/24(수) 19:00 ~ 22:00 (3시간)**
- 장소: 원종이 회사 건물(?) 또는 선릉역 [더모임](http://www.ienbiz.com/) 또는 [마음동네](https://maumtownhub.modoo.at/)
  - 더모임: 1시간/1인당 2,200원 (+모니터 필요시 대여 시간당 1,500원, 화이트보드/음료는 무료제공)
  - 마음동네: 문의 필요(02-851-1934)
- 참석자(예정): 서승현, 조원종, 김덕주
- 내용: 프로젝트 진행 방향 논의 및 계획 수립 등
- 준비사항: 스터디 공간대여비, 과제(#6)

시간이랑 장소에 대한 의견을 받습니다!

**Comment by wonjong85** [comment]
간단히는 가능할 거 같아!

**Comment by tea7day** [comment]
### 모임에서 물어볼 거 정리
- Q) iOS virtual device에서 드래그는 어떻게 하는지?
- Q) 컴포넌트별 영역 확인은 어떻게?

**Comment by tea7day** [comment]
완료됨

### 진행 사항
- 깃헙 이슈 검토
- 원종이 모바일 프로젝트 검토
- 프로젝트 구성 논의
- amplify 시연

### 참석자
- @wonjong85 @tea7day 

### 다음 모임 준비 사항
- 김밥 등 먹을 거리 미리 준비
