### ISSUE TITLE
Redux vs Mobx

### ISSUE THREAD

**Issue by wonjong85** [tea7day/primorsk#13]
## Redux vs Mobx 비교
* [Mobx vs Redux](https://www.educba.com/mobx-vs-redux/)
* [React에서 Mobx 경험기 (Redux와 비교기)](http://woowabros.github.io/experience/2019/01/02/kimcj-react-mobx.html)

**Comment by tea7day** [comment]
- [React에서 Mobx 경험기 (Redux와 비교기)](http://woowabros.github.io/experience/2019/01/02/kimcj-react-mobx.html)

내용은 좋아보이는 너무 길어서 먼저 공유하고 시간 좀 날 때 읽어보려고ㅎㅎ

우리는 redux로 시작해보고~ 다음 프로젝트는 mobx를 써보는걸로?
