### ISSUE TITLE
husky 추가로 인한 commit시 내용

### ISSUE THREAD

**Issue by wonjong85** [tea7day/primorsk#38]
## husky란?
* 뭐하는 아이인고...?

## 커밋시 내용
Warning: Setting pre-commit script in package.json > scripts will be deprecated
Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
Or run ./node_modules/.bin/husky-upgrade for automatic update

See https://github.com/typicode/husky for usage

husky > pre-commit (node v10.13.0)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ✔ Running linters...
[wonjong c002e5c] - shared > colors, fonts, strings 추가
 4 files changed, 11 insertions(+)
 create mode 100644 packages/shared/colors.tsx
 create mode 100644 packages/shared/fonts.tsx
 create mode 100644 packages/shared/strings.tsx

**Comment by tea7day** [comment]
[husky](https://github.com/typicode/husky)는 js 프로젝트에서 [github hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) 기능을 제공해주는 라이브러리인데
주로 [lint-staged](https://github.com/okonet/lint-staged)와 연동해서 깃 커밋을 하기전에 린팅과 포매팅 등을 자동으로 적용하기 위해 쓰여

협업 시, 통일된 코드 스타일을 유지하기 위해 `prettier`같은 포매팅 도구를 사용하지만, 이것도 강제하지 않으면
  사용자에 따라서 적용될 수도 안 될 수도 있으니까. 커밋 전에 무조건 적용하게끔 강제하는거지 :)

**Comment by wonjong85** [comment]
> [husky](https://github.com/typicode/husky)는 js 프로젝트에서 [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) 기능을 제공해주는 라이브러리인데
> 주로 [lint-staged](https://github.com/okonet/lint-staged)와 연동해서 깃 커밋을 하기전에 린팅과 포매팅 등을 자동으로 적용하기 위해 쓰여
> 
> 협업 시, 통일된 코드 스타일을 유지하기 위해 `prettier`같은 포매팅 도구를 사용하지만, 이것도 강제하지 않으면
> 사용자에 따라서 적용될 수도 안 될 수도 있으니까. 커밋 전에 무조건 적용하게끔 강제하는거지 :)
> 
> 위의 warning이 나는 이유는 `husky` 최신 버전에서는 설정하는 위치가 조금 변경되었는데
> 우리 프로젝트는 예전 버전처럼 `package.json`의 `pre-commit` 스크립트로 설정되어 있어서 나는 거야.
> 이것도 tslint를 eslint로 변경하면서 가치 바꿔야지 이렇게
> <img alt="Screen Shot 2019-05-06 at 8 10 14 PM" width="893" src="https://user-images.githubusercontent.com/28684130/57221662-002f6c00-703b-11e9-96ed-01d3ae34511d.png">
> 
> * [설정 방법 참고](https://github.com/typicode/husky#install)

**Comment by wonjong85** [comment]
> [husky](https://github.com/typicode/husky)는 js 프로젝트에서 [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) 기능을 제공해주는 라이브러리인데
> 주로 [lint-staged](https://github.com/okonet/lint-staged)와 연동해서 깃 커밋을 하기전에 린팅과 포매팅 등을 자동으로 적용하기 위해 쓰여
> 
> 협업 시, 통일된 코드 스타일을 유지하기 위해 `prettier`같은 포매팅 도구를 사용하지만, 이것도 강제하지 않으면
> 사용자에 따라서 적용될 수도 안 될 수도 있으니까. 커밋 전에 무조건 적용하게끔 강제하는거지 :)
> 
> 위의 warning이 나는 이유는 `husky` 최신 버전에서는 설정하는 위치가 조금 변경되었는데
> 우리 프로젝트는 예전 버전처럼 `package.json`의 `pre-commit` 스크립트로 설정되어 있어서 나는 거야.
> 이것도 tslint를 eslint로 변경하면서 가치 바꿔야지 이렇게
> <img alt="Screen Shot 2019-05-06 at 8 10 14 PM" width="893" src="https://user-images.githubusercontent.com/28684130/57221662-002f6c00-703b-11e9-96ed-01d3ae34511d.png">
> 
> * [설정 방법 참고](https://github.com/typicode/husky#install)

오케이요!
