### ISSUE TITLE
[궁금해] 이슈를 활성화 시키자

### ISSUE THREAD

**Issue by tea7day** [tea7day/primorsk#39]
프로젝트를 진행하면서 각자가 궁금한 것들을 
`궁금해` 레이블을 설정한 이슈로 부담없이 `많이많이` 만들면 좋을 꺼 같아.
(질문 종류나 수준을 상관하지말고)

아는 사람이 댓글로 자기가 아는 내용을 달아줘도 좋고, 본인이 찾은 답을 달아도 좋고!
프로젝트를 진행하면서 필요한 지식을 서로가 효과적으로 향상시킬 수 있는 방법이 될 꺼 같아.

어떤가 다들?

**Comment by wonjong85** [comment]
좋아!

**Comment by deokju** [comment]
좋은 방법이긴 한데.. 흐음... 이슈 사용방법을 아직 잘 모르겠다능

**Comment by tea7day** [comment]
이슈는 내용을 너무 신경쓰지말고, 
무조건 많이 만들어보는게 좋아~ 그러다보면 감도오고
또 같이하다보면 맞춰지니까

무조건 많이 만들어보는게 좋음
