### ISSUE TITLE
React Native 프로젝트 구조는 어떻게 가져가야하는가?

### ISSUE THREAD

**Issue by tea7day** [tea7day/primorsk#5]
### Boilerplates

- [SOLID MOBILE APPLICATIONS WITH OUR REACT NATIVE BOILERPLATE](https://thecodingmachine.io/introducing-the-react-native-boilerplate)
- [Ignite-bowser](https://github.com/infinitered/ignite)
   - Ignite에서 제공하는 기본 보일러플레이트
- [Ignite-boilerplates](https://github.com/infinitered/ignite/blob/master/BOILERPLATES.md)
   - Ignite에서 제공하는 보일러플레이트 목록
- [react-native-starter-kit](https://github.com/mcnamee/react-native-starter-kit)
- [react-native-boilerplate](https://github.com/victorkvarghese/react-native-boilerplate)

### 참고

- [How to structure your project and manage static resources in React Native](https://medium.freecodecamp.org/how-to-structure-your-project-and-manage-static-resources-in-react-native-6f4cfc947d92)
- [Best practices for creating React Native apps](https://medium.com/react-native-training/best-practices-for-creating-react-native-apps-part-1-66311c746df3)
- [React Native Styling: Structure for Style Organization](https://thoughtbot.com/blog/structure-for-styling-in-react-native)
- [ignite](https://github.com/infinitered/ignite)
- [How To Structure a React Native App For Scale](https://medium.com/the-andela-way/how-to-structure-a-react-native-app-for-scale-a29194cd33fc)
- [Our template for building a React Native mobile app](https://blog.moove-it.com/template-building-react-native-mobile-app/)
- [React Native Styling: Structure for Style Organization](https://thoughtbot.com/blog/structure-for-styling-in-react-native)

> 원종이 회사 실무 프로젝트 구조도 참고

**Comment by TRQ1** [comment]
제시된 article 참고했는대...

개인적으로는 

아래 aricle에서 제시해주는 구조가 나아보여, 하지만. 원종님 구조를 들어보고 결정해도 늦지 않을듯...
https://medium.com/the-andela-way/how-to-structure-a-react-native-app-for-scale-a29194cd33fc
