### ISSUE TITLE
[5회 모임 안내] 06/11(화) 19:00

### ISSUE THREAD

**Issue by wonjong85** [tea7day/primorsk#55]
- 시간: **19/06/11(화) 19:00 ~ 22:00 (3시간)**
- 장소: 선릉역 부근 [FastFive](https://map.naver.com/?pinId=1981388967&dlevel=10&enc=b64&pinType=site&y=042a4fb2752b086a4ed8934e53a58a6b&x=5fbbb56aa174b6069f64d443f9976e7f) 건물 1층
- 참석자(예정): 서승현, 조원종, 김덕주, 이규원
- 내용: `AWS Amplify`를 사용한 커스텀 로그인 화면 구현

**Comment by tea7day** [comment]
`mobx`, `mobx-state-tree` 공부하고 오면 수월할 듯

**Comment by wooritech** [comment]
완료

### 진행 내용
- [ignite-bowser-examples](https://github.com/infinitered/ignite-bowser-examples) 분석
  - `mobx`, `mobx-state-tree`, `react-navigator` 등

**Comment by tea7day** [comment]
완료

- [ignite-bowser-examples](https://github.com/infinitered/ignite-bowser-examples)
   -  `mobx`, `mobx-state-tree`, `react-navigation` 등
