### ISSUE TITLE
[7회 모임 안내] 6/25(화) 19:00

### ISSUE THREAD

**Issue by wonjong85** [tea7day/primorsk#59]
- 장소: 선릉역 부근 [FastFive](https://map.naver.com/?pinId=1981388967&dlevel=10&enc=b64&pinType=site&y=042a4fb2752b086a4ed8934e53a58a6b&x=5fbbb56aa174b6069f64d443f9976e7f)
- 참석자: 조원종, 서승현, 이규원

**Comment by wonjong85** [comment]
1. 현재 vsCode에 설정되어 있는 prettier 설정하는 방법은?
2. react-native PixelRatio에 포함된 함수를 꼭 써야되는가?
3. Story는 언제 쓰는걸까?

**Comment by tea7day** [comment]
1. 해야하는데 아직 시도를 안해봄. 참고로 현재 prettier설정은 .prettierrc가 아닌 package.json에 되어있음.
2. 모르겠다.
3. story는 UI 컴포넌트 개발 및 테스트 도구인 [storybook](https://storybook.js.org/)에서 사용됨

**Comment by wonjong85** [comment]
- 프로젝트 구조변경 후 기존 로그인화면 병합
